server:
  servlet:
    context-path: /
  port: 9080
  compression:
    mime-types:
      - application/json

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5433/cartao
    username: cartao
    password: cartao
    continue-on-error: true

  application:
    name: cartoes-ms
  jpa:
    open-in-view: false
    show-sql: true
    format-sql: true
    hibernate:
      format-sql: true
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          batch_size: 50
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-local.xml
